sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

# cache node modules
cache:
    directories:
        - $HOME/.npm
        - node_modules

matrix:
    include:
        - node_js: '8'
          script: npm run pretest
          env: CI=pretest
        - node_js: '8'
          script: npm run test-only
          env: CI=coverage 8
        - node_js: '6'
          script: npm run test-only
          env: CI=tests 6
        - node_js: '4'
          script: npm run test-only
          env: CI=tests 4
          sudo: required

before_install:
    - npm install -g npm@latest
    - npm i -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

after_script: greenkeeper-lockfile-upload

after_success:
    - if [ "$CI" = "coverage" ]; then npm run coveralls; fi
