sudo: false

language: node_js

node_js:
    - '7'
    - '6'
    - '5'
    - '4'

cache:
    directories:
        - node_modules

before_install:
    - npm prune
    - npm update

after_success: npm run coveralls
